#ifndef _H_PUNK_AUDIO_DISTANCE_MODELS
#define _H_PUNK_AUDIO_DISTANCE_MODELS

namespace Audio
{
	enum class DistanceModel { 
		NONE, 
		INVERSE_DISTANCE, 
		INVERSE_DISTANCE_CLAMPED, 
		LINEAR_DISTANCE, 
		LINEAR_DISTANCE_CLAMPED, 
		EXPONENT_DISTANCE, 
		EXPONENT_DISTANCE_CLAMPED
	};
}
	
#endif	//	_H_PUNK_AUDIO_DISTANCE_MODELS