#ifndef _H_PUNK_OPENGL_NVX_GPU_MEMORY_INFO
#define _H_PUNK_OPENGL_NVX_GPU_MEMORY_INFO

#define GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX          0x9047
#define GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX    0x9048
#define GPU_MEMORY_INFO_CURRENT_AVAILABLE_VIDMEM_NVX  0x9049
#define GPU_MEMORY_INFO_EVICTION_COUNT_NVX            0x904A
#define GPU_MEMORY_INFO_EVICTED_MEMORY_NVX            0x904B
        
#endif	//	_H_PUNK_OPENGL_NVX_GPU_MEMORY_INFO