#ifndef _H_PUNK_MATH_MODULE
#define _H_PUNK_MATH_MODULE

#include "vec3.h"
#include "vec2.h"
#include "vec4.h"
#include "mat2.h"
#include "mat3.h"
#include "mat4.h"
#include "smart_matrix.h"
#include "plane.h"
#include "line3d.h"
#include "line2d.h"
#include "triangle2d.h"
#include "triangle3d.h"
#include "aabb.h"
#include "low_level_math.h"
#include "interpolation.h"
#include "complex.h"
#include "frustum.h"
#include "matrix.h"
#include "random.h"
#include "noise.h"
#include "constants.h"
#include "oct_tree.h"
#include "helper.h"
#include "rect.h"
#include "bounding_box.h"
#include "bounding_sphere.h"
#include "graph/module.h"
#include "perspective_decoder.h"
#include "recount.h"
#include "spherical.h"

#endif
