######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 19:53:26 2013
######################################################################

QMAKE_CXXFLAGS += -std=c++11 -pipe

CONFIG -= QT

win32 {
    DEFINES += _WIN32
}

DEFINES += PUNK_ENGINE_EXPORTS USE_OPENGL USE_PNG USE_ZLIB USE_OPENEXR USE_JPEG  USE_FREETYPE USE_LIB_TIFF

contains(DEFINES, USE_OPENGL) {
#   USE_GRASS_RC
#   USE_TERRAIN_RC
#   USE_WATER_RC
DEFINES += USE_SOLID_COLOR_RC
DEFINES += USE_SOLID_VERTEX_COLOR_RC
DEFINES += USE_SOLID_TEXTURE_3D_RC
DEFINES += USE_LIGHT_PER_VERTEX_DIFFUSE
DEFINES += USE_LIGHT_PER_FRAGMENT_DIFFUSE
DEFINES += USE_RC_PVRTDL    # Render context per vertex texture diffuse lighting
DEFINES += USE_RC_PFRTDL    # Render context per fragment texture diffuse lighting
DEFINES += USE_BUMP_MAPPING_RC
DEFINES += USE_SKINNING_RC
DEFINES += USE_SHADOW_MAPS

}

contains(DEFINES, USE_PNG)
{
DEFINES += USE_ZLIB
}

win32 {
    LIBS += -lgdi32 -lopengl32 -lOle32 -lstrmiids -lDbgHelp -lOleAut32 -lvfw32 -lcomdlg32
}

unix {

LIBS += -lGL -lXext -lX11 -lXxf86vm

contains (DEFINES, USE_PNG)
{
    LIBS += -lpng
}

contains (DEFINES, USE_JPEG)
{
    LIBS += -ljpeg
}

contains (DEFINES, USE_LIB_TIFF)
{
    LIBS += -ltiff
}

contains (DEFINES, USE_ZLIB)
{
    #LIBS += -lzip2
}

contains (DEFINES, USE_FREETYPE)
{
    LIBS += -lfreetype
    INCLUDEPATH += "/usr/include/freetype2"
}

contains (DEFINES, USE_OPENEXR)
{
    #LIBS += -lopenexr
}

contains (DEFINES, USE_NOISE)
{
    LIBS += -lnoise
}

}

contains(DEFINES, USE_NEVER) {
HEADERS += ../../source/tests/test_create_opengl_window/test_create_opengl_window.h \
           ../../source/tools/texture_generator/checker.h \
           ../../source/tools/texture_generator/generator.h \
           ../../source/tools/texture_generator/noise.h \
           ../../source/tools/viewer/viewer.h \
           ../../source/translator/echo_module/echo_module.h \
           ../../source/tools/bullet_maker/main.cpp \
           ../../source/tools/food_maker/main.cpp \
           ../../source/tools/height_map_maker/main.cpp \
           ../../source/tools/texture_generator/checker.cpp \
           ../../source/tools/texture_generator/generator.cpp \
           ../../source/tools/texture_generator/main.cpp \
           ../../source/tools/texture_generator/noise.cpp \
           ../../source/tools/vao_cooker/main.cpp \
           ../../source/tools/viewer/main.cpp \
           ../../source/tools/weapon_maker/main.cpp \
           ../../source/tests/main.cpp \
           ../../source/translator/console_interpretator.cpp
}

contains(DEFINES, USE_OPENGL) {
    HEADERS += ../../source/gpu/opengl/buffers/ibo.h \
           ../../source/gpu/opengl/buffers/module.h \
           ../../source/gpu/opengl/buffers/pbo.h \
           ../../source/gpu/opengl/buffers/template_buffer.h \
           ../../source/gpu/opengl/buffers/vbo.h \
           ../../source/gpu/opengl/driver/gl_driver.h \
           ../../source/gpu/opengl/driver/module.h \
           ../../source/gpu/opengl/driver/video_memory.h \
           ../../source/gpu/opengl/error/gl_error_check.h \
           ../../source/gpu/opengl/error/gl_exceptions.h \
           ../../source/gpu/opengl/error/module.h \
           ../../source/gpu/opengl/gl/ati_meminfo.h \
           ../../source/gpu/opengl/gl/extensions.h \
           ../../source/gpu/opengl/gl/glcorearb.h \
           ../../source/gpu/opengl/gl/module.h \
           ../../source/gpu/opengl/gl/nvx_gpu_memory_info.h \
           ../../source/gpu/opengl/gl/wglext.h \
           ../../source/gpu/opengl/nvtristrip/nv_tri_strip.h \
           ../../source/gpu/opengl/nvtristrip/nv_tri_strip_objects.h \
           ../../source/gpu/opengl/nvtristrip/vertex_cache.h \
           ../../source/gpu/opengl/painter/gl_paint_device.h \
           ../../source/gpu/opengl/painter/gl_paint_engine.h \
           ../../source/gpu/opengl/painter/gl_painter.h \
           ../../source/gpu/opengl/painter/module.h \           
           ../../source/gpu/opengl/render/gl_render.h \
           ../../source/gpu/opengl/render_context/gl_render_context.h \
           ../../source/gpu/opengl/render_context/module.h \
           ../../source/gpu/opengl/render_context/rc_bump_mapping.h \
           ../../source/gpu/opengl/render_context/rc_grass.h \
           ../../source/gpu/opengl/render_context/rc_gui.h \
           ../../source/gpu/opengl/render_context/rc_painter.h \
           ../../source/gpu/opengl/render_context/rc_particle_system.h \
           ../../source/gpu/opengl/render_context/rc_skinning.h \           
           ../../source/gpu/opengl/render_context/rc_solid_textured_3d.h \
           ../../source/gpu/opengl/render_context/rc_terrain.h \
           ../../source/gpu/opengl/render_context/render_contexts.h \           
           ../../source/gpu/opengl/render_targets/module.h \           
           ../../source/gpu/opengl/renderable/gl_primitive_type.h \
           ../../source/gpu/opengl/renderable/module.h \
           ../../source/gpu/opengl/textures/internal_formats.h \
           ../../source/gpu/opengl/textures/module.h \           
           ../../source/gpu/opengl/textures/texture2d_impl.h \
           ../../source/gpu/opengl/textures/texture2d_pbo_impl.h \
           ../../source/gpu/opengl/textures/texture_2d_manager.h \           
           ../../source/gpu/opengl/render_context/shaders/shader.h \
           ../../source/gpu/opengl/render_context/shaders/shaders.h \
           ../../source/gpu/opengl/renderable/primitives/vertex_array_object.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_bump.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_grass.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_gui.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_light.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_painter.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_particle.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_skinning.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_solid_color.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_solid_textured.h \
           ../../source/gpu/opengl/render_context/shaders/fragment/fs_terrain.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_bump.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_grass.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_gui.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_light.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_painter.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_particle.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_particle_system.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_solid_color.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_terrain.h \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_transform_3d.h \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_transformed_textured_3d.h \
	    ../../source/gpu/opengl/render_context/rc_per_fragment_lighting.h \
	    ../../source/gpu/opengl/render_context/rc_pvtdl.h \
	    ../../source/gpu/opengl/render_context/rc_pftdl.h \
	    ../../source/gpu/opengl/gl/gl_blending.h \
	    ../../source/gpu/opengl/render_context/rc_dynamic.h \
	   ../../source/gpu/opengl/attribute_configer.h \
	   ../../source/gpu/opengl/module.h    \
	    ../../source/gpu/opengl/render_context/shaders/vertex/vs_solid_vertex_color.h \
            ../../source/gpu/opengl/render_context/shaders/fragment/fs_solid_vertex_color.h \
            ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting.h \
            ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting_diffuse.h \
            ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_vertex_lighting_diffuse.h \
            ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_vertex_lighting_tex_diffuse.h \
            ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting_tex_diffuse.h


SOURCES +=  ../../source/gpu/opengl/render_context/rc_per_fragment_lighting.cpp \
	    ../../source/gpu/opengl/render_context/shaders/fragment/fs_solid_vertex_color.cpp \
	    ../../source/gpu/opengl/render_context/rc_pvtdl.cpp \
	    ../../source/gpu/opengl/render_context/rc_pftdl.cpp \
	    ../../source/gpu/opengl/gl/gl_blending.cpp \
            ../../source/gpu/opengl/gl/extensions.cpp \
	    ../../source/gpu/opengl/render_context/rc_dynamic.cpp \	    
	    ../../source/gpu/opengl/render_context/shaders/vertex/vs_solid_vertex_color.cpp \
	   ../../source/gpu/opengl/attribute_configer.cpp \
	   ../../source/gpu/opengl/gpu_opengl_module.cpp \
	   ../../source/gpu/opengl/module.cpp \
	   ../../source/gpu/opengl/buffers/ibo.cpp \
	   ../../source/gpu/opengl/buffers/pbo.cpp \
	   ../../source/gpu/opengl/buffers/vbo.cpp \
	   ../../source/gpu/opengl/driver/gl_driver.cpp \
	   ../../source/gpu/opengl/driver/video_memory.cpp \
	   ../../source/gpu/opengl/error/gl_error_check.cpp \
	   ../../source/gpu/opengl/error/gl_exceptions.cpp \
	   ../../source/gpu/opengl/nvtristrip/nv_tri_strip.cpp \
	   ../../source/gpu/opengl/nvtristrip/nv_tri_strip_objects.cpp \
	   ../../source/gpu/opengl/nvtristrip/vertex_cache.cpp \
	   ../../source/gpu/opengl/painter/gl_paint_engine.cpp \
	   ../../source/gpu/opengl/render_context/gl_render_context.cpp \
	   ../../source/gpu/opengl/render_context/rc_bump_mapping.cpp \
	   ../../source/gpu/opengl/render_context/rc_grass.cpp \
	   ../../source/gpu/opengl/render_context/rc_gui.cpp \
	   ../../source/gpu/opengl/render_context/rc_painter.cpp \
	   ../../source/gpu/opengl/render_context/rc_particle_system.cpp \
	   ../../source/gpu/opengl/render_context/rc_skinning.cpp \	   
	   ../../source/gpu/opengl/render_context/rc_solid_textured_3d.cpp \
	   ../../source/gpu/opengl/render_context/rc_terrain.cpp \
	   ../../source/gpu/opengl/render_context/rc_per_vertex_lighting.cpp \
	   ../../source/gpu/opengl/render_context/render_contexts.cpp \	   	   
	   ../../source/gpu/opengl/renderable/gl_primitive_type.cpp \
	   ../../source/gpu/opengl/textures/internal_formats.cpp \	   	   
	   ../../source/gpu/opengl/render_context/shaders/shader.cpp \
	   ../../source/gpu/opengl/renderable/primitives/vertex_array_object.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_bump.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_grass.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_gui.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_light.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_painter.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_particle.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_skinning.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_solid_color.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_solid_textured.cpp \
	   ../../source/gpu/opengl/render_context/shaders/fragment/fs_terrain.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_bump.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_grass.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_gui.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_light.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_painter.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_particle.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_particle_system.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_solid_color.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_terrain.cpp \
	   ../../source/gpu/opengl/render_context/shaders/vertex/vs_transform_3d.cpp \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_transformed_textured_3d.cpp \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting.cpp \
           ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting_diffuse.cpp \
            ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_vertex_lighting_diffuse.cpp \
            ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting_tex_diffuse.cpp \
            ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_vertex_lighting_tex_diffuse.cpp
}

SOURCES += ../../source/main.cpp \
	   ../../source/application/application.cpp \
	   ../../source/audio/audio_buffer.cpp \
	   ../../source/audio/audio_config.cpp \
	   ../../source/audio/audio_listener.cpp \
	   ../../source/audio/audio_ogg_loader.cpp \
	   ../../source/audio/audio_ogg_processor.cpp \
	   ../../source/audio/audio_source.cpp \
	   ../../source/audio/sound_system.cpp \
	   ../../source/generator/generator.cpp \
	   ../../source/gpu/gpu_config.cpp \
	   ../../source/gpu/gpu_module.cpp \
	   ../../source/gui/manager.cpp \
	   ../../source/gui/widget.cpp \
	   ../../source/images/image_file.cpp \
	   ../../source/images/png_file.cpp \
	   ../../source/math/aabb.cpp \
	   ../../source/math/astar.cpp \
	   ../../source/math/bounding_box.cpp \
	   ../../source/math/bounding_sphere.cpp \
	   ../../source/math/clip_space.cpp \
	   ../../source/math/convex_shape_mesh.cpp \
	   ../../source/math/ellipsoid.cpp \
	   ../../source/math/frustum.cpp \
	   ../../source/math/helper.cpp \
	   ../../source/math/line2d.cpp \
	   ../../source/math/line3d.cpp \
	   ../../source/math/math.cpp \
	   ../../source/math/math_error.cpp \
	   ../../source/math/noise.cpp \
	   ../../source/math/noiseutils.cpp \
	   ../../source/math/oct_tree.cpp \
	   ../../source/math/plane.cpp \
	   ../../source/math/portal.cpp \
	   ../../source/math/random.cpp \
	   ../../source/math/rect.cpp \
	   ../../source/math/relations.cpp \
	   ../../source/math/root_find.cpp \
	   ../../source/math/sphere.cpp \
	   ../../source/math/triangle2d.cpp \
	   ../../source/math/triangle3d.cpp \
	   ../../source/physics/physical_simulator.cpp \
	   ../../source/physics/physics_config.cpp \
	   ../../source/physics/physics_terrain.cpp \
	   ../../source/raytracer/render.cpp \
	   ../../source/raytracer/scene.cpp \
	   ../../source/render/bbox_render.cpp \
	   ../../source/render/character_render.cpp \
	   ../../source/render/render_config.cpp \
	   ../../source/render/solid_object_render.cpp \	   
           ../../source/scene/node.cpp \
	   ../../source/scene/scene_graph.cpp \
	   ../../source/string/string.cpp \
	   ../../source/system/binary_file.cpp \
	   ../../source/system/buffer.cpp \
	   ../../source/system/clock.cpp \
	   ../../source/system/compound_object.cpp \
	   ../../source/system/config_file.cpp \
	   ../../source/system/environment.cpp \
	   ../../source/system/event_manager.cpp \
	   ../../source/system/factory.cpp \
	   ../../source/system/folder.cpp \
	   ../../source/system/hresource.cpp \
	   ../../source/system/logger.cpp \
	   ../../source/system/object.cpp \
	   ../../source/system/pool_manager.cpp \
	   ../../source/system/profiler.cpp \
	   ../../source/system/storable.cpp \
	   ../../source/system/timer.cpp \
	   ../../source/virtual/building.cpp \
	   ../../source/virtual/scheme.cpp \
	   ../../source/virtual/sound.cpp \
	   ../../source/audio/openal/al_buffer_impl.cpp \
	   ../../source/audio/openal/al_distance_models.cpp \
	   ../../source/audio/openal/al_error.cpp \
	   ../../source/audio/openal/al_format.cpp \
	   ../../source/audio/openal/al_listener_impl.cpp \
	   ../../source/audio/openal/al_sound_system_impl.cpp \
	   ../../source/audio/openal/al_source_impl.cpp \
	   ../../source/audio/openal/alext.cpp \
	   ../../source/gpu/common/abstract_render_context_policy.cpp \
	   ../../source/gpu/common/gpu_common_module.cpp \
	   ../../source/gpu/common/gpu_state.cpp \	   
	   ../../source/gpu/common/renderable.cpp \
	   ../../source/gpu/common/renderable_builder.cpp \
	   ../../source/gpu/error/gpu_excpetions.cpp \
	   ../../source/gpu/opencl/cl_buffer.cpp \
	   ../../source/gpu/opencl/cl_command_queue.cpp \
	   ../../source/gpu/opencl/cl_context.cpp \
	   ../../source/gpu/opencl/cl_device.cpp \
	   ../../source/gpu/opencl/cl_kernel.cpp \
	   ../../source/gpu/opencl/cl_platform.cpp \
	   ../../source/gpu/opencl/cl_program.cpp \	   
	   ../../source/gpu/painter/brush.cpp \
	   ../../source/gpu/painter/paint_device.cpp \
	   ../../source/gpu/painter/paint_engine.cpp \
	   ../../source/gpu/painter/painter.cpp \
	   ../../source/gpu/painter/pen.cpp \
	   ../../source/gui/events/focused.cpp \
	   ../../source/gui/events/mouse_enter.cpp \
	   ../../source/gui/events/mouse_leave.cpp \
	   ../../source/gui/events/unfocused.cpp \
	   ../../source/images/converter/yuy2_to_rgb.cpp \
	   ../../source/images/import_export/exporter.cpp \
	   ../../source/images/import_export/importer.cpp \
	   ../../source/images/import_export/jpg_importer.cpp \
	   ../../source/images/import_export/png_exporter.cpp \
	   ../../source/images/import_export/png_importer.cpp \
	   ../../source/images/internal_images/gray_image.cpp \
	   ../../source/images/internal_images/image.cpp \
	   ../../source/images/internal_images/rgb_image.cpp \
	   ../../source/images/internal_images/rgba_image.cpp \
	   ../../source/physics/bullet/bullet_motion_state.cpp \
	   ../../source/physics/bullet/bullet_physical_simulator.cpp \
	   ../../source/physics/bullet/bullet_rigid_body.cpp \
	   ../../source/physics/bullet/bullet_shape_body.cpp \
	   ../../source/physics/bullet/bullet_terrain.cpp \
	   ../../source/physics/simple/simple_motion_state.cpp \
	   ../../source/physics/simple/simple_physical_simulator.cpp \
	   ../../source/physics/simple/simple_rigid_body.cpp \
	   ../../source/physics/simple/simple_shape_body.cpp \
	   ../../source/physics/simple/simple_terrain.cpp \
	   ../../source/render/v1/mesh_cooker.cpp \
	   ../../source/render/v1/ogl_gui_render.cpp \
	   ../../source/render/v1/simple_render.cpp \
	   ../../source/scene/events/new_instance_appeared_event.cpp \
	   ../../source/scene/events/parent_changed_event.cpp \	   
	   ../../source/system/concurrency/process.cpp \
	   ../../source/system/concurrency/semaphore.cpp \
	   ../../source/system/concurrency/thread.cpp \
           ../../source/system/concurrency/monitor.cpp \
	   ../../source/system/concurrency/thread_job.cpp \
	   ../../source/system/concurrency/thread_mutex.cpp \
	   ../../source/system/concurrency/thread_pool.cpp \
	   ../../source/system/errors/assert2.cpp \
	   ../../source/system/errors/error.cpp \
	   ../../source/system/errors/exceptions.cpp \
	   ../../source/system/errors/stack_trace.cpp \
	   ../../source/system/events/events.cpp \
	   ../../source/system/events/idle_event.cpp \
	   ../../source/system/events/key_char_event.cpp \
	   ../../source/system/events/key_down_event.cpp \
	   ../../source/system/events/key_up_event.cpp \
	   ../../source/system/events/key_wchar_event.cpp \
	   ../../source/system/events/model_time_step_event.cpp \
	   ../../source/system/events/mouse_hoover_event.cpp \
	   ../../source/system/events/mouse_left_button_down.cpp \
	   ../../source/system/events/mouse_left_button_up.cpp \
	   ../../source/system/events/mouse_middle_button_down.cpp \
	   ../../source/system/events/mouse_middle_button_up.cpp \
	   ../../source/system/events/mouse_move_event.cpp \
	   ../../source/system/events/mouse_right_button_down.cpp \
	   ../../source/system/events/mouse_right_button_up.cpp \
	   ../../source/system/events/mouse_wheel_event.cpp \
	   ../../source/system/events/window_resize_event.cpp \
	   ../../source/system/input/camera_capture.cpp \
	   ../../source/system/input/console.cpp \
	   ../../source/system/input/keyboard.cpp \
	   ../../source/system/input/mouse.cpp \
	   ../../source/system/streaming/async_loader.cpp \
	   ../../source/system/types/list.cpp \
	   ../../source/translator/echo_module/echo_module.cpp \
	   ../../source/utility/descriptors/action_desc.cpp \
	   ../../source/utility/descriptors/animation_desc.cpp \
	   ../../source/utility/descriptors/armature_desc.cpp \
	   ../../source/utility/descriptors/bone_desc.cpp \
	   ../../source/utility/descriptors/camera_desc.cpp \
	   ../../source/utility/descriptors/light_desc.cpp \
	   ../../source/utility/descriptors/material_desc.cpp \
	   ../../source/utility/descriptors/mesh_desc.cpp \
	   ../../source/utility/descriptors/object_desc.cpp \
	   ../../source/utility/descriptors/object_type_desc.cpp \
	   ../../source/utility/descriptors/world_desc.cpp \
	   ../../source/utility/fonts/font_builder.cpp \
	   ../../source/utility/parser/base_parser2.cpp \
	   ../../source/utility/parser/game_parser.cpp \
	   ../../source/virtual/animation/action.cpp \
	   ../../source/virtual/animation/action_male_walk.cpp \
	   ../../source/virtual/animation/animation.cpp \
	   ../../source/virtual/animation/animation_mixer.cpp \
	   ../../source/virtual/animation/armature_animation_mixer.cpp \
	   ../../source/virtual/animation/bone_animation.cpp \
	   ../../source/virtual/animation/object_animation.cpp \
	   ../../source/virtual/animation/object_animation_mixer.cpp \
	   ../../source/virtual/controllers/camera_controller.cpp \
	   ../../source/virtual/data/camera.cpp \
	   ../../source/virtual/data/entity.cpp \
	   ../../source/virtual/data/geometry.cpp \
	   ../../source/virtual/data/light.cpp \
	   ../../source/virtual/data/light_set.cpp \
	   ../../source/virtual/data/material.cpp \
	   ../../source/virtual/data/proxy.cpp \
	   ../../source/virtual/data/skin_geometry.cpp \
	   ../../source/virtual/data/static_geometry.cpp \
	   ../../source/virtual/data/transform.cpp \
	   ../../source/virtual/data/world.cpp \
	   ../../source/virtual/manager/camera_manager.cpp \
	   ../../source/virtual/manager/material_manager.cpp \
	   ../../source/virtual/motions/motion_strategy.cpp \
	   ../../source/virtual/motions/static_motion_strategy.cpp \
	   ../../source/virtual/skinning/armature.cpp \
	   ../../source/virtual/skinning/bone.cpp \
	   ../../source/virtual/skinning/human_armature.cpp \
	   ../../source/virtual/skinning/human_female_armature.cpp \
	   ../../source/virtual/skinning/human_male_armature.cpp \
	   ../../source/virtual/terrain/terrain.cpp \
	   ../../source/virtual/terrain/terrain_cell.cpp \
	   ../../source/virtual/terrain/terrain_data.cpp \
	   ../../source/virtual/terrain/terrain_loader.cpp \
	   ../../source/virtual/terrain/terrain_manager.cpp \
	   ../../source/virtual/terrain/terrain_observer.cpp \
	   ../../source/virtual/terrain/terrain_processor.cpp \
	   ../../source/virtual/terrain/terrain_streamer.cpp \
	   ../../source/virtual/terrain/terrain_view.cpp \
	   ../../source/virtual/terrain/terrain_view_loader.cpp \
	   ../../source/virtual/terrain/terrain_view_processor.cpp \
	   ../../source/gpu/opencl/errors/cl_exceptions.cpp \	   
	   ../../source/virtual/data/lights/point_light.cpp \
	   ../../source/virtual/objects/characters/human.cpp \
	   ../../source/virtual/objects/characters/male_human.cpp \
	   ../../source/virtual/objects/simple/solid_cube.cpp \	   
	../../source/system/handler.cpp \			
	../../source/gpu/common/primitives/triangles.cpp \
        ../../source/gpu/common/primitives/triangle_strip.cpp \
        ../../source/gpu/common/primitives/triangle_fans.cpp \
	../../source/gpu/common/primitives/static_mesh.cpp \
	../../source/gpu/common/primitives/sphere_mesh.cpp \
	../../source/gpu/common/primitives/skin_mesh.cpp \
	../../source/gpu/common/primitives/scaled_grid.cpp \
	../../source/gpu/common/primitives/quad_mesh.cpp \
	../../source/gpu/common/primitives/points.cpp \
	../../source/gpu/common/primitives/lines.cpp \
	../../source/gpu/common/primitives/grid_object.cpp \
	../../source/gpu/common/primitives/cube_mesh.cpp \
        ../../source/gpu/common/primitives/frustum_mesh.cpp \
	../../source/gpu/common/primitive_type.cpp \
	../../source/gpu/common/video_driver.cpp \
	../../source/gpu/common/lighting/light_model.cpp \
	../../source/gpu/common/lighting/light_parameters.cpp \
	../../source/gpu/common/material/gpu_material.cpp \        
        ../../source/gpu/common/fog/fog.cpp \
        ../../source/gpu/common/fog/fog_mode.cpp \
	../../source/math/graph/graph.cpp \
	../../source/math/graph/graph_vertex.cpp \
        ../../source/math/graph/graph_edge.cpp \
        ../../source/gpu/common/frame.cpp \
    ../../source/images/import_export/openexr_importer.cpp \
    ../../source/virtual/terrain/terrain_mesh.cpp \
    ../../source/math/curve.cpp \
    ../../source/math/spline.cpp \
    ../../source/math/weighted_point.cpp \
    ../../source/utility/parser/parse_simple.cpp \
    ../../source/utility/parser/parse_bbox.cpp \
    ../../source/utility/parser/parse_convex_mesh.cpp \
    ../../source/utility/parser/parse_bone_weights.cpp \
    ../../source/utility/parser/parse_position_track.cpp \
    ../../source/utility/parser/parse_rotation_track.cpp \
    ../../source/utility/parser/parse_animation.cpp \
    ../../source/utility/parser/parse_action.cpp \
    ../../source/utility/parser/parse_static_meshes.cpp \
    ../../source/utility/parser/parse_bone.cpp \
    ../../source/utility/parser/parse_armature.cpp \
    ../../source/utility/parser/parse_textures.cpp \
    ../../source/utility/parser/parse_static_mesh.cpp \
    ../../source/utility/parser/parse_skin_mesh.cpp \
    ../../source/utility/parser/parse_skin_meshes.cpp \
    ../../source/utility/parser/parse_material.cpp \
    ../../source/utility/parser/parse_materials.cpp \
    ../../source/utility/parser/parse_location_indoor.cpp \
    ../../source/utility/parser/parse_terrain_raw_data_source.cpp \
    ../../source/utility/parser/parse_terrain_cell.cpp \
    ../../source/utility/parser/parse_map_description.cpp \
    ../../source/utility/parser/parse_anything.cpp \
    ../../source/utility/parser/parse_punk_file.cpp \
    ../../source/utility/parser/parse_navi_mesh.cpp \
    ../../source/ai/curvepath.cpp \
    ../../source/utility/parser/parse_curve_path.cpp \
    ../../source/utility/parser/parse_spline.cpp \
    ../../source/utility/parser/parse_weighted_point.cpp \
    ../../source/ai/navi_mesh.cpp \
    ../../source/virtual/data/texture_slot.cpp \
    ../../source/utility/parser/parse_texture_slot.cpp \
    ../../source/virtual/water/river.cpp \
    ../../source/virtual/data/lights/sun.cpp \
    ../../source/utility/parser/parse_scene.cpp \
    ../../source/utility/parser/parse_sun.cpp \
    ../../source/render/v2/render_v2.cpp \
    ../../source/utility/parser/parse_terrain_mesh.cpp \
    ../../source/utility/parser/parse_river.cpp \
    ../../source/scene/selector/selector.cpp \
    ../../source/math/perspective_decoder.cpp \
    ../../source/math/mat4.cpp \
    ../../source/math/vec4.cpp \
    ../../source/math/frustum_plane.cpp \
    ../../source/scene/selector/selection.cpp \
    ../../source/images/import_export/tiff_importer.cpp \
    ../../source/system/window/window_win32.cpp \
    ../../source/system/window/window_linux.cpp \
    ../../source/system/pool.cpp \
    ../../source/render/v2/render_static_mesh.cpp \
    ../../source/render/v2/render_skin_mesh.cpp \
    ../../source/render/v2/render_armature.cpp \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_text_solid.cpp \
    ../../source/gpu/common/shadow_model.cpp \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_depth.cpp \                
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_bump_shadow_map.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_bump_shadow_map.cpp \
    ../../source/system/rtti.cpp \
    ../../source/system/serializable.cpp \
    ../../source/utility/serializer/serializer.cpp \
    ../../source/system/static_information.cpp \
    ../../source/math/mat2.cpp \
    ../../source/math/mat3.cpp \
    ../../source/math/vec3.cpp \
    ../../source/math/quat.cpp \
    ../../source/math/vec2.cpp \
    ../../source/utility/parser/parse_scene_node.cpp \
    ../../source/render/v2/render_river.cpp \
    ../../source/render/v2/process_armature.cpp \
    ../../source/render/v2/process_light.cpp \
    ../../source/render/v2/process_material.cpp \
    ../../source/render/v2/process_terrain_mesh.cpp \
    ../../source/render/v2/process_sun.cpp \
    ../../source/render/v2/process_navi_mesh.cpp \
    ../../source/scene/scene_helper.cpp \
    ../../source/utility/async_parser.cpp \
    ../../source/utility/path_finder.cpp \
    ../../source/render/v2/process_transform.cpp \
    ../../source/gpu/common/frame_buffer/frame_buffer_config.cpp \
    ../../source/gpu/opengl/render_targets/gl_query_supprted_frame_buffer_configs.cpp \
    ../../source/gpu/common/frame_buffer/frame_buffer.cpp \
    ../../source/gpu/opengl/render_targets/gl_frame_buffer.cpp \
    ../../source/gpu/common/frame_buffer/render_buffer.cpp \
    ../../source/gpu/common/frame_buffer/depth_render_buffer.cpp \
    ../../source/gpu/common/frame_buffer/color_render_buffer.cpp \
    ../../source/gpu/opengl/render_targets/gl_depth_render_buffer.cpp \
    ../../source/gpu/opengl/render_targets/gl_color_render_buffer.cpp \
    ../../source/gpu/opengl/driver/gl_capabilities.cpp \
    ../../source/gpu/common/frame_buffer/render_buffer_config.cpp \
    ../../source/gpu/common/texture/texture_context.cpp \
    ../../source/gpu/common/texture/text_surface.cpp \
    ../../source/gpu/common/texture/texture2d.cpp \
    ../../source/gpu/opengl/textures/texture_convert.cpp \
    ../../source/gpu/opengl/textures/texture2d_pbo_impl.cpp \
    ../../source/gpu/opengl/render/gl_shadow_map_render.cpp \
    ../../source/gpu/common/render/render_pass.cpp \
    ../../source/gpu/common/render/render_batch.cpp \
    ../../source/gpu/common/texture/texture2d_array.cpp \
    ../../source/gpu/opengl/textures/gl_texture2d_array.cpp \
    ../../source/gpu/common/texture/texture.cpp \
    ../../source/gpu/common/frame_buffer/frame_buffer_target.cpp \
    ../../source/gpu/opengl/render_targets/gl_frame_buffer_convert.cpp \
    ../../source/gpu/common/shaders/shader_builder.cpp \    
    ../../source/gpu/common/shaders/shader_data_type.cpp \
    ../../source/gpu/common/shaders/shader_uniform_table.cpp \
    ../../source/gpu/common/shaders/shader_var_table.cpp \
    ../../source/gpu/common/shaders/shader_function.cpp \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_shadow_single.cpp \
    ../../source/gpu/opengl/render_context/shaders/gl_shader_type.cpp \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_solid_textured_2d_array.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_depth.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_fragment_lighting_tex_diffuse.cpp \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_fragment_lighting_tex_diffuse.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_fragment_lighting_diffuse.cpp \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_fragment_lighting_diffuse.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_skinning_bump.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_skinning_depth.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_pfl_diffuse_simple_shadow.cpp \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_pfl_diffuse_simple_shadow.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting_diffuse_shadow_simple.cpp \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_vertex_lighting_diffuse_shadow_simple.cpp \
    ../../source/gpu/common/render/abstract_shadowmap_render.cpp \
    ../../source/gpu/common/render/cascade_shadow_map_render.cpp \
    ../../source/gpu/common/render/simple_shadowmap_render.cpp \
    ../../source/gpu/common/render/shadow_map_render_type.cpp \
    ../../source/gpu/common/render/abstract_shadow_map_debug_visualizer.cpp \
    ../../source/gpu/common/render/cascade_shadow_map_debug_visualizer.cpp \
    ../../source/gpu/common/render/shadow_render_common.cpp \
    ../../source/gpu/opengl/driver/gl_vfs.cpp \
    ../../source/math/recount.cpp \
    ../../source/math/spherical.cpp \
    ../../source/application/viewer_application.cpp \
    ../../source/system/keymap.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting_diffuse_specular.cpp \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_fragment_lighting_diffuse_specular.cpp \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_fragment_lighting_diffuse_specular.cpp


# Input
HEADERS += ../../source/config.h \
           ../../source/punk_engine.h \
	   ../../source/ai/navi_mesh.h \
	   ../../source/ai/navi_triangle.h \
	   ../../source/application/application.h \
	   ../../source/application/application_config.h \
	   ../../source/application/module.h \
	   ../../source/audio/audio_buffer.h \
	   ../../source/audio/audio_config.h \
	   ../../source/audio/audio_distance_model.h \
	   ../../source/audio/audio_format.h \
	   ../../source/audio/audio_listener.h \
	   ../../source/audio/audio_loader.h \
	   ../../source/audio/audio_ogg_loader.h \
	   ../../source/audio/audio_ogg_processor.h \
	   ../../source/audio/audio_source.h \
	   ../../source/audio/punk_audio.h \
	   ../../source/audio/resource.h \
	   ../../source/audio/sound_system.h \
	   ../../source/generator/generator.h \
	   ../../source/gpu/gpu_config.h \
	   ../../source/gpu/module.h \
	   ../../source/gui/gui_adapter.h \
	   ../../source/gui/gui_render.h \
	   ../../source/gui/interface.h \
	   ../../source/gui/manager.h \
	   ../../source/gui/module.h \
	   ../../source/gui/widget.h \
	   ../../source/images/formats.h \
	   ../../source/images/image_file.h \
	   ../../source/images/module.h \
	   ../../source/images/png_file.h \
	   ../../source/math/aabb.h \
	   ../../source/math/astar.h \
	   ../../source/math/bounding_box.h \
	   ../../source/math/bounding_shere.h \
	   ../../source/math/catmull_rom_spline.h \
	   ../../source/math/clip_space.h \
	   ../../source/math/complex.h \
	   ../../source/math/constants.h \
	   ../../source/math/convex_shape_mesh.h \
	   ../../source/math/ellipsoid.h \
	   ../../source/math/frustum.h \
	   ../../source/math/header_matrix.h \
	   ../../source/math/helper.h \
	   ../../source/math/interpolation.h \
	   ../../source/math/line2d.h \
	   ../../source/math/line3d.h \
	   ../../source/math/low_level_math.h \
	   ../../source/math/mat2.h \
	   ../../source/math/mat3.h \
	   ../../source/math/mat4.h \
	   ../../source/math/math.h \
	   ../../source/math/math_error.h \
	   ../../source/math/matrix.h \
	   ../../source/math/module.h \
	   ../../source/math/noise.h \
	   ../../source/math/noiseutils.h \
	   ../../source/math/nrm.h \
	   ../../source/math/oct_tree.h \
	   ../../source/math/plane.h \
	   ../../source/math/polygon.h \
	   ../../source/math/polygon3d.h \
	   ../../source/math/portal.h \
	   ../../source/math/quat.h \
	   ../../source/math/random.h \
	   ../../source/math/ray.h \
	   ../../source/math/rect.h \
	   ../../source/math/region.h \
	   ../../source/math/relations.h \
	   ../../source/math/root_find.h \
	   ../../source/math/smart_matrix.h \
	   ../../source/math/sphere.h \
	   ../../source/math/triangle2d.h \
	   ../../source/math/triangle3d.h \
	   ../../source/math/type.h \
	   ../../source/math/vec2.h \
	   ../../source/math/vec3.h \
	   ../../source/math/vec4.h \
	   ../../source/physics/interface.h \
	   ../../source/physics/module.h \
	   ../../source/physics/physical_simulator.h \
	   ../../source/physics/physics_adapter.h \
	   ../../source/physics/physics_config.h \
	   ../../source/physics/physics_terrain.h \
	   ../../source/physics/rigid_body.h \
	   ../../source/physics/shape_body.h \
	   ../../source/raytracer/point.h \
	   ../../source/raytracer/raytracer.h \
	   ../../source/raytracer/render.h \
	   ../../source/raytracer/render_impl1.h \
	   ../../source/raytracer/render_impl2.h \
	   ../../source/raytracer/scene.h \
	   ../../source/raytracer/scene_impl1.h \
	   ../../source/raytracer/scene_impl2.h \
	   ../../source/render/bbox_render.h \
	   ../../source/render/character_render.h \
	   ../../source/render/module.h \
	   ../../source/render/render_config.h \
	   ../../source/render/solid_object_render.h \
	   ../../source/scene/interface.h \
	   ../../source/scene/module.h \
	   ../../source/scene/node.h \	   
	   ../../source/scene/scene_graph.h \	   	   
	   ../../source/string/string.h \
	   ../../source/system/allocator.h \           
	   ../../source/system/binary_file.h \
	   ../../source/system/buffer.h \
	   ../../source/system/clock.h \
	   ../../source/system/compound_object.h \
	   ../../source/system/config_file.h \
	   ../../source/system/decl_property.h \
	   ../../source/system/environment.h \
	   ../../source/system/event_manager.h \
	   ../../source/system/factory.h \
	   ../../source/system/folder.h \
	   ../../source/system/handler.h \
	   ../../source/system/hresource.h \
	   ../../source/system/logger.h \
	   ../../source/system/module.h \
	   ../../source/system/object.h \
	   ../../source/system/pool.h \
	   ../../source/system/pool_manager.h \
	   ../../source/system/poolable.h \
	   ../../source/system/profiler.h \
	   ../../source/system/resource.h \
	   ../../source/system/resource_creator.h \
	   ../../source/system/serializable.h \
	   ../../source/system/state_manager.h \
	   ../../source/system/storable_data.h \
	   ../../source/system/timer.h \	   
	   ../../source/tests/test_interface.h \
	   ../../source/translator/console_interpretator.h \
	   ../../source/translator/module.h \
	   ../../source/types/string.h \
	   ../../source/types/types.h \
	   ../../source/utility/module.h \
	   ../../source/virtual/building.h \
	   ../../source/virtual/interface.h \
	   ../../source/virtual/intersection.h \
	   ../../source/virtual/module.h \
	   ../../source/virtual/scheme.h \
	   ../../source/virtual/sound.h \
	   ../../source/virtual/track_pos.h \
	   ../../source/virtual/data/lights/point_light.h \
	   ../../source/virtual/objects/characters/human.h \
	   ../../source/virtual/objects/characters/human_impl.h \
	   ../../source/virtual/objects/characters/male_human.h \
	   ../../source/virtual/objects/characters/male_human_impl.h \
	   ../../source/virtual/objects/simple/module.h \
	   ../../source/virtual/objects/simple/solid_cube.h \
	   ../../source/audio/openal/al_buffer_impl.h \
	   ../../source/audio/openal/al_distance_models.h \
	   ../../source/audio/openal/al_error.h \
	   ../../source/audio/openal/al_format.h \
	   ../../source/audio/openal/al_listener_impl.h \
	   ../../source/audio/openal/al_sound_system_impl.h \
	   ../../source/audio/openal/al_source_impl.h \
	   ../../source/audio/openal/alext.h \
	   ../../source/audio/openal/openal.h \
	   ../../source/gpu/common/abstract_render_context_policy.h \
	   ../../source/gpu/common/frame.h \
	   ../../source/gpu/common/gpu_state.h \
	   ../../source/gpu/common/module.h \
	   ../../source/gpu/common/primitive_type.h \	   
	   ../../source/gpu/common/renderable.h \
	   ../../source/gpu/common/renderable_builder.h \
	   ../../source/gpu/common/vertex.h \
	   ../../source/gpu/common/vertex_component.h \
	   ../../source/gpu/common/video_driver.h \
	   ../../source/gpu/error/gpu_exceptions.h \
	   ../../source/gpu/error/module.h \
	   ../../source/gpu/opencl/cl_buffer.h \
	   ../../source/gpu/opencl/cl_buffer_impl.h \
	   ../../source/gpu/opencl/cl_command_queue.h \
	   ../../source/gpu/opencl/cl_command_queue_impl.h \
	   ../../source/gpu/opencl/cl_context.h \
	   ../../source/gpu/opencl/cl_context_impl.h \
	   ../../source/gpu/opencl/cl_device.h \
	   ../../source/gpu/opencl/cl_device_impl.h \
	   ../../source/gpu/opencl/cl_kernel.h \
	   ../../source/gpu/opencl/cl_kernel_impl.h \
	   ../../source/gpu/opencl/cl_platform.h \
	   ../../source/gpu/opencl/cl_platform_impl.h \
	   ../../source/gpu/opencl/cl_program.h \
	   ../../source/gpu/opencl/cl_program_impl.h \
	   ../../source/gpu/opencl/module.h \
	   ../../source/gpu/painter/brush.h \
	   ../../source/gpu/painter/module.h \
	   ../../source/gpu/painter/paint_device.h \
	   ../../source/gpu/painter/paint_engine.h \
	   ../../source/gpu/painter/painter.h \
	   ../../source/gpu/painter/pen.h \
	   ../../source/gui/events/focused.h \
	   ../../source/gui/events/interface.h \
	   ../../source/gui/events/module.h \
	   ../../source/gui/events/mouse_enter.h \
	   ../../source/gui/events/mouse_leave.h \
	   ../../source/gui/events/unfocused.h \
	   ../../source/images/converter/yuy2_to_rgb.h \
	   ../../source/images/error/image_exceptions.h \
	   ../../source/images/error/module.h \
	   ../../source/images/import_export/exporter.h \
	   ../../source/images/import_export/importer.h \
	   ../../source/images/import_export/importer_impl.h \
	   ../../source/images/import_export/jpg_importer.h \
	   ../../source/images/import_export/png_exporter.h \
	   ../../source/images/import_export/png_importer.h \
	   ../../source/images/internal_images/component.h \
	   ../../source/images/internal_images/gray_image.h \
	   ../../source/images/internal_images/image.h \
	   ../../source/images/internal_images/image_impl.h \
	   ../../source/images/internal_images/rgb_image.h \
	   ../../source/images/internal_images/rgba_image.h \
	   ../../source/physics/bullet/bullet_adapter.h \
	   ../../source/physics/bullet/bullet_motion_state.h \
	   ../../source/physics/bullet/bullet_physical_simulator.h \
	   ../../source/physics/bullet/bullet_plain.h \
	   ../../source/physics/bullet/bullet_rigid_body.h \
	   ../../source/physics/bullet/bullet_shape_body.h \
	   ../../source/physics/bullet/bullet_terrain.h \
	   ../../source/physics/bullet/module.h \
	   ../../source/physics/error/module.h \
	   ../../source/physics/error/physics_exception.h \
	   ../../source/physics/simple/module.h \
	   ../../source/physics/simple/simple_adapter.h \
	   ../../source/physics/simple/simple_motion_state.h \
	   ../../source/physics/simple/simple_physical_simulator.h \
	   ../../source/physics/simple/simple_plain.h \
	   ../../source/physics/simple/simple_rigid_body.h \
	   ../../source/physics/simple/simple_shape_body.h \
	   ../../source/physics/simple/simple_terrain.h \
	   ../../source/render/v1/mesh_cooker.h \
	   ../../source/render/v1/module.h \
	   ../../source/render/v1/ogl_gui_render.h \
	   ../../source/render/v1/simple_render.h \
	   ../../source/scene/events/new_instance_appeared_event.h \
	   ../../source/scene/events/parent_changed_event.h \	   
	   ../../source/system/aop/aop.h \
	   ../../source/system/concurrency/atomic.h \
           ../../source/system/concurrency/atomicint.h \
	   ../../source/system/concurrency/module.h \
	   ../../source/system/concurrency/monitor.h \
	   ../../source/system/concurrency/monitor_scope.h \
	   ../../source/system/concurrency/os_handle.h \
	   ../../source/system/concurrency/process.h \
	   ../../source/system/concurrency/semaphore.h \
	   ../../source/system/concurrency/thread.h \
	   ../../source/system/concurrency/thread_job.h \
	   ../../source/system/concurrency/thread_mutex.h \
	   ../../source/system/concurrency/thread_pool.h \
	   ../../source/system/errors/assert2.h \
	   ../../source/system/errors/error.h \
	   ../../source/system/errors/exceptions.h \
	   ../../source/system/errors/module.h \
	   ../../source/system/errors/stack_trace.h \
	   ../../source/system/events/event.h \
	   ../../source/system/events/event_type.h \
	   ../../source/system/events/events.h \
	   ../../source/system/events/idle_event.h \
	   ../../source/system/events/interface.h \
	   ../../source/system/events/key_char_event.h \
	   ../../source/system/events/key_down_event.h \
	   ../../source/system/events/key_up_event.h \
	   ../../source/system/events/key_wchar_event.h \
	   ../../source/system/events/model_time_step_event.h \
	   ../../source/system/events/mouse_hoover_event.h \
	   ../../source/system/events/mouse_left_button_down.h \
	   ../../source/system/events/mouse_left_button_up.h \
	   ../../source/system/events/mouse_middle_button_down.h \
	   ../../source/system/events/mouse_middle_button_up.h \
	   ../../source/system/events/mouse_move_event.h \
	   ../../source/system/events/mouse_right_button_down.h \
	   ../../source/system/events/mouse_right_button_up.h \
	   ../../source/system/events/mouse_wheel_event.h \
	   ../../source/system/events/window_resize_event.h \
	   ../../source/system/input/camera_capture.h \
	   ../../source/system/input/console.h \
	   ../../source/system/input/keyboard.h \
	   ../../source/system/input/module.h \
	   ../../source/system/input/mouse.h \
	   ../../source/system/signal_slot/signal_slot.h \
	   ../../source/system/smart_pointers/module.h \
	   ../../source/system/smart_pointers/proxy.h \
	   ../../source/system/smart_pointers/ref_count.h \
	   ../../source/system/smart_pointers/weak_ref.h \
	   ../../source/system/streaming/async_loader.h \
	   ../../source/system/streaming/data_loader.h \
	   ../../source/system/streaming/data_processor.h \
	   ../../source/system/streaming/module.h \
	   ../../source/system/streaming/resource_request.h \
	   ../../source/system/types/list.h \
	   ../../source/system/types/priority_list.h \
	   ../../source/system/window/module.h \
	   ../../source/system/window/window.h \
	   ../../source/system/window/window_adapter.h \
	   ../../source/utility/descriptors/action_desc.h \
	   ../../source/utility/descriptors/anim_track_desc.h \
	   ../../source/utility/descriptors/animation_desc.h \
	   ../../source/utility/descriptors/armature_desc.h \
	   ../../source/utility/descriptors/bone_desc.h \
	   ../../source/utility/descriptors/camera_desc.h \
	   ../../source/utility/descriptors/descriptors.h \
	   ../../source/utility/descriptors/indoor_desc.h \
	   ../../source/utility/descriptors/light_desc.h \
	   ../../source/utility/descriptors/material_desc.h \
	   ../../source/utility/descriptors/mesh_desc.h \
	   ../../source/utility/descriptors/object_desc.h \
	   ../../source/utility/descriptors/object_type_desc.h \
	   ../../source/utility/descriptors/world_desc.h \
	   ../../source/utility/fonts/font_builder.h \
	   ../../source/utility/model/vertex_bone_weight.h \
	   ../../source/utility/model/vertex_index.h \
	   ../../source/utility/parser/base_parser2.h \
	   ../../source/utility/parser/game_parser.h \
	   ../../source/utility/parser/keywords.h \
	   ../../source/utility/parser/parser.h \
	   ../../source/virtual/animation/action.h \
	   ../../source/virtual/animation/action_male_walk.h \
	   ../../source/virtual/animation/animation.h \
	   ../../source/virtual/animation/animation_mixer.h \
	   ../../source/virtual/animation/animation_track.h \
	   ../../source/virtual/animation/armature_animation_mixer.h \
	   ../../source/virtual/animation/bone_animation.h \
	   ../../source/virtual/animation/interface.h \
	   ../../source/virtual/animation/module.h \
	   ../../source/virtual/animation/object_animation.h \
	   ../../source/virtual/animation/object_animation_mixer.h \
	   ../../source/virtual/controllers/camera_controller.h \
	   ../../source/virtual/controllers/controllers.h \
	   ../../source/virtual/data/camera.h \
	   ../../source/virtual/data/door.h \
	   ../../source/virtual/data/entity.h \
	   ../../source/virtual/data/geometry.h \
	   ../../source/virtual/data/interface.h \
	   ../../source/virtual/data/interior_location.h \
	   ../../source/virtual/data/light.h \
	   ../../source/virtual/data/light_set.h \
	   ../../source/virtual/data/location.h \
	   ../../source/virtual/data/material.h \
	   ../../source/virtual/data/material_manager.h \
	   ../../source/virtual/data/module.h \
	   ../../source/virtual/data/old_shape_mesh.h \
	   ../../source/virtual/data/proxy.h \
	   ../../source/virtual/data/skin_geometry.h \
	   ../../source/virtual/data/static_geometry.h \
	   ../../source/virtual/data/transform.h \
	   ../../source/virtual/data/world.h \
	   ../../source/virtual/manager/camera_manager.h \
	   ../../source/virtual/manager/manager.h \
	   ../../source/virtual/manager/material_manager.h \
	   ../../source/virtual/motions/key_based_strategy.h \
	   ../../source/virtual/motions/motion.h \
	   ../../source/virtual/motions/motion_strategy.h \
	   ../../source/virtual/motions/static_motion_strategy.h \
	   ../../source/virtual/objects/module.h \
	   ../../source/virtual/skinning/armature.h \
	   ../../source/virtual/skinning/bone.h \
	   ../../source/virtual/skinning/bone_frame.h \
	   ../../source/virtual/skinning/human_armature.h \
	   ../../source/virtual/skinning/human_female_armature.h \
	   ../../source/virtual/skinning/human_male_armature.h \
	   ../../source/virtual/skinning/interface.h \
	   ../../source/virtual/skinning/module.h \
	   ../../source/virtual/skinning/types.h \
	   ../../source/virtual/terrain/interface.h \
	   ../../source/virtual/terrain/module.h \
	   ../../source/virtual/terrain/terrain.h \
	   ../../source/virtual/terrain/terrain_cell.h \
	   ../../source/virtual/terrain/terrain_data.h \
	   ../../source/virtual/terrain/terrain_loader.h \
	   ../../source/virtual/terrain/terrain_manager.h \
	   ../../source/virtual/terrain/terrain_observer.h \
	   ../../source/virtual/terrain/terrain_processor.h \
	   ../../source/virtual/terrain/terrain_streamer.h \
	   ../../source/virtual/terrain/terrain_view.h \
	   ../../source/virtual/terrain/terrain_view_loader.h \
	   ../../source/virtual/terrain/terrain_view_processor.h \    
    ../../source/gpu/common/primitives/triangle_strip.h \
    ../../source/gpu/common/primitives/triangle_fans.h \
    ../../source/gpu/common/primitives/static_mesh.h \
    ../../source/gpu/common/primitives/sphere_mesh.h \
    ../../source/gpu/common/primitives/skin_mesh.h \
    ../../source/gpu/common/primitives/scaled_grid.h \
    ../../source/gpu/common/primitives/quad_mesh.h \
    ../../source/gpu/common/primitives/points.h \
    ../../source/gpu/common/primitives/lines.h \
    ../../source/gpu/common/primitives/grid_object.h \
    ../../source/gpu/common/primitives/cube_mesh.h \
    ../../source/gpu/common/primitives/frustum_mesh.h \
    ../../source/gpu/common/primitives/module.h \
    ../../source/gpu/common/primitives/triangles.h \
    ../../source/gpu/common/lighting/light_model.h \
    ../../source/gpu/common/lighting/module.h \
    ../../source/gpu/common/lighting/light_parameters.h \    
    ../../source/gpu/common/config.h \
    ../../source/gpu/common/material/module.h \
    ../../source/gpu/common/material/gpu_material.h \    
    ../../source/gpu/common/fog/fog.h \
    ../../source/gpu/common/fog/fog_mode.h \
    ../../source/gpu/common/fog/module.h \
    ../../source/math/graph/graph.h \
    ../../source/math/graph/graph_vertex.h \
    ../../source/math/graph/graph_edge.h \
    ../../source/math/graph/module.h \
    ../../source/images/import_export/openexr_importer.h \
    ../../source/virtual/terrain/terrain_mesh.h \
    ../../source/math/curve.h \
    ../../source/math/spline.h \
    ../../source/math/weighted_point.h \
    ../../source/utility/parser/parse_functions.h \
    ../../source/ai/module.h \
    ../../source/ai/curvepath.h \
    ../../source/virtual/data/texture_slot.h \
    ../../source/virtual/water/river.h \
    ../../source/virtual/water/module.h \
    ../../source/virtual/water/interface.h \
    ../../source/virtual/data/lights/sun.h \
    ../../source/render/v2/render_v2.h \
    ../../source/render/v2/module.h \
    ../../source/scene/selector/selector.h \
    ../../source/math/perspective_decoder.h \
    ../../source/math/frustum_plane.h \
    ../../source/scene/selector/selection.h \
    ../../source/ai/interface.h \
    ../../source/images/import_export/tiff_importer.h \
    ../../source/render/v2/render_static_mesh.h \
    ../../source/render/v2/render_skin_mesh.h \
    ../../source/render/v2/render_armature.h \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_text_solid.h \
    ../../source/gpu/common/shadow_model.h \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_depth.h \            
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_bump_shadow_map.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_bump_shadow_map.h \
    ../../source/system/rtti.h \
    ../../source/system/static_information.h \
    ../../source/utility/serializer/serializer.h \
    ../../source/engine_objects.h \
    ../../source/render/v2/render_river.h \
    ../../source/render/v2/process_armature.h \
    ../../source/render/v2/process_light.h \
    ../../source/render/v2/process_material.h \
    ../../source/render/v2/process_terrain_mesh.h \
    ../../source/render/v2/process_sun.h \
    ../../source/render/v2/process_navi_mesh.h \
    ../../source/scene/scene_helper.h \
    ../../source/utility/async_parser.h \
    ../../source/utility/path_finder.h \
    ../../source/render/v2/process_transform.h \
    ../../source/gpu/common/frame_buffer/frame_buffer_config.h \
    ../../source/gpu/common/frame_buffer/module.h \
    ../../source/gpu/common/frame_buffer/frame_buffer.h \
    ../../source/gpu/opengl/render_targets/gl_frame_buffer.h \
    ../../source/gpu/common/frame_buffer/render_buffer.h \
    ../../source/gpu/common/frame_buffer/depth_render_buffer.h \
    ../../source/gpu/common/frame_buffer/color_render_buffer.h \
    ../../source/gpu/opengl/render_targets/gl_depth_render_buffer.h \
    ../../source/gpu/opengl/render_targets/gl_color_render_buffer.h \
    ../../source/gpu/opengl/driver/gl_capabilities.h \
    ../../source/gpu/common/frame_buffer/render_buffer_config.h \
    ../../source/gpu/common/texture/texture2d.h \
    ../../source/gpu/common/texture/texture_context.h \
    ../../source/gpu/common/texture/text_surface.h \
    ../../source/gpu/common/texture/module.h \
    ../../source/gpu/common/texture/texture_filter.h \
    ../../source/gpu/common/texture/texture_wrap.h \
    ../../source/gpu/common/texture/texture_compare_func.h \
    ../../source/gpu/common/texture/texture_compare_mode.h \
    ../../source/gpu/opengl/textures/texture_convert.h \
    ../../source/gpu/common/video_driver_caps.h \
    ../../source/gpu/opengl/render/gl_shadow_map_render.h \
    ../../source/gpu/common/render/render_pass.h \
    ../../source/gpu/common/render/render_batch.h \
    ../../source/gpu/common/render/module.h \
    ../../source/gpu/common/texture/texture2d_array.h \
    ../../source/gpu/opengl/textures/gl_texture2d_array.h \
    ../../source/gpu/common/texture/texture.h \
    ../../source/gpu/common/frame_buffer/frame_buffer_target.h \
    ../../source/gpu/opengl/render_targets/gl_frame_buffer_convert.h \
    ../../source/gpu/common/shaders/shader_builder.h \
    ../../source/gpu/common/shaders/shader_type.h \
    ../../source/gpu/common/shaders/module.h \
    ../../source/gpu/common/shaders/shader_data_type.h \
    ../../source/gpu/common/shaders/shader_uniform_table.h \
    ../../source/gpu/common/shaders/shader_var_table.h \
    ../../source/gpu/common/shaders/shader_function.h \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_shadow_single.h \
    ../../source/gpu/opengl/render_context/shaders/gl_shader_type.h \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_solid_textured_2d_array.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_depth.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_fragment_lighting_tex_diffuse.h \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_fragment_lighting_tex_diffuse.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_fragment_lighting_diffuse.h \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_fragment_lighting_diffuse.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_skinning_bump.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_skinning_depth.h \
    ../../source/math/frustum_points.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_pfl_diffuse_simple_shadow.h \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_pfl_diffuse_simple_shadow.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting_diffuse_shadow_simple.h \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_vertex_lighting_diffuse_shadow_simple.h \
    ../../source/gpu/common/render/abstract_shadowmap_render.h \
    ../../source/gpu/common/render/cascade_shadow_map_render.h \
    ../../source/gpu/common/render/simple_shadowmap_render.h \
    ../../source/gpu/common/render/shadow_map_render_type.h \
    ../../source/gpu/common/render/abstract_shadow_map_debug_visualizer.h \
    ../../source/gpu/common/render/cascade_shadow_map_debug_visualizer.h \
    ../../source/gpu/common/render/shadow_render_common.h \
    ../../source/gpu/opengl/driver/gl_vfs.h \
    ../../source/math/recount.h \
    ../../source/math/spherical.h \
    ../../source/application/viewer_application.h \
    ../../source/system/keymap.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_vertex_lighting_diffuse_specular.h \
    ../../source/gpu/opengl/render_context/shaders/vertex/vs_per_fragment_lighting_diffuse_specular.h \
    ../../source/gpu/opengl/render_context/shaders/fragment/fs_per_fragment_lighting_diffuse_specular.h


CONFIG += dll
TEMPLATE = lib
TARGET = punk_engine

release:OBJECTS_DIR = release/.obj
release:MOC_DIR = release/.moc
release:RCC_DIR = release/.rcc
release:UI_DIR = release/.ui

#DESTDIR = ../../bin/debug

debug:OBJECTS_DIR = debug/.obj
debug:MOC_DIR = debug/.moc
debug:RCC_DIR = debug/.rcc
debug:UI_DIR = debug/.ui

debug:DEFINES += _DEBUG
release:DEFINES += _NDEBUG

release:MYDLLDIR = $IN_PWD/../../../bin/release
debug:MYDLLDIR = $IN_PWD/../../../bin/debug

DESTDIR = \"$$MYDLLDIR\"

DDIR = \"$$MYDLLDIR/\"
SDIR = \"$$IN_PWD/\"

win32:file ~= s,/,\\,g
win32:DDIR ~= s,/,\\,g
win32:SDIR ~= s,/,\\,g

#for(file, HEADERS) {
#    QMAKE_POST_LINK += $$QMAKE_COPY $$quote($${SDIR}$${file}) $$quote($$DDIR) $$escape_expand(\\n\\t)
#}

OTHER_FILES += \
    ../../data/shaders/text_color_330.frag \
    ../../data/shaders/terrain_330.vert \
    ../../data/shaders/terrain_330.frag \
    ../../data/shaders/terrain_330 - Copy.vert \
    ../../data/shaders/terrain_330 - Copy.frag \
    ../../data/shaders/static_mesh_330.vert \
    ../../data/shaders/static_mesh_330.frag \
    ../../data/shaders/solid_vertex_color.vert \
    ../../data/shaders/solid_vertex_color.frag \
    ../../data/shaders/solid_textured_330.vert \
    ../../data/shaders/solid_textured_330.frag \
    ../../data/shaders/solid_color_3d_330.vert \
    ../../data/shaders/solid_color_3d_330.frag \
    ../../data/shaders/solid_color_2d_330.vert \
    ../../data/shaders/solid_color_2d_330.frag \
    ../../data/shaders/skinning_330.frag \
    ../../data/shaders/shaders.ini \
    ../../data/shaders/quad_330.geom \
    ../../data/shaders/per_vertex_lighting_tex_diffuse_330.vert \
    ../../data/shaders/per_vertex_lighting_tex_diffuse_330.frag \
    ../../data/shaders/per_vertex_lighting_diffuse_330.vert \
    ../../data/shaders/per_vertex_lighting_diffuse_330.frag \
    ../../data/shaders/per_vertex_lighting_330.vert \
    ../../data/shaders/per_vertex_lighting_330.frag \
    ../../data/shaders/per_fragment_lighting_tex_diffuse_330.vert \
    ../../data/shaders/per_fragment_lighting_tex_diffuse_330.frag \
    ../../data/shaders/per_fragment_lighting_diffuse_330.vert \
    ../../data/shaders/per_fragment_lighting_diffuse_330.frag \
    ../../data/shaders/particle_330.vert \
    ../../data/shaders/particle_330.frag \
    ../../data/shaders/painter_330.vert \
    ../../data/shaders/painter_330.frag \
    ../../data/shaders/normals_330.vert \
    ../../data/shaders/normals_330.frag \
    ../../data/shaders/line_330.vert \
    ../../data/shaders/line_330.frag \
    ../../data/shaders/line_3d_330.vert \
    ../../data/shaders/line_3d_330.frag \
    ../../data/shaders/line_2d_330.vert \
    ../../data/shaders/line_2d_330.frag \
    ../../data/shaders/gui_330.vert \
    ../../data/shaders/gui_330.frag \
    ../../data/shaders/grass_330.vert \
    ../../data/shaders/grass_330.frag \
    ../../data/shaders/draw_normals.vert \
    ../../data/shaders/draw_normals.frag \
    ../../data/shaders/depth.frag \
    ../../data/shaders/bump_330.vert \
    ../../data/shaders/bump_330.frag \
    ../../data/shaders/bump_330_shadow_map.vert \
    ../../data/shaders/bump_330_shadow_map.frag \
    ../../data/shaders/solid_texture_2d_array.frag \
    ../../data/shaders/depth.vert \
    ../../data/shaders/skinning_bump_330.vert \
    ../../data/shaders/skinning_depth_330.vert \
    ../../data/shaders/per_fragment_lighting_diffuse_simple_shadow.vert \
    ../../data/shaders/per_fragment_lighting_diffuse_simple_shadow.frag \
    ../../data/shaders/per_vertex_lighting_diffuse_simple_shadow.vert \
    ../../data/shaders/per_vertex_lighting_diffuse_simple_shadow.frag \
    ../../data/shaders/light.glsl \
    ../../data/shaders/per_fragment_lighting_diffuse_specular_330.vert \
    ../../data/shaders/per_fragment_lighting_diffuse_specular_330.frag \
    ../../data/shaders/material.glsl

