#ifndef _H_PUNK_OPENGL_PRIMITIVES_TYPES
#define _H_PUNK_OPENGL_PRIMITIVES_TYPES

namespace OpenGL
{
	enum PrimitiveTypes {
		NONE,
		QUAD,
		SKIN_MESH,
		STATIC_MESH
	};
}

#endif	//	_H_PUNK_OPENGL_PRIMITIVES_TYPES