#ifndef _H_PUNK_VIRTUAL_KEY_WORDS
#define _H_PUNK_VIRTUAL_KEY_WORDS

namespace Utility
{
	enum KeywordCode
	{
		WORD_BAD_KEYWORD,
		WORD_OPEN_BRACKET,
		WORD_CLOSE_BRACKET,
		WORD_OBJECT,
		WORD_BOUNDING_BOX,
		WORD_LOCATION,
		WORD_WORLD_MATRIX,
		WORD_LOCAL_MATRIX,
		WORD_MESH,
		WORD_VERTEX_POSITION,
		WORD_NORMALS,
		WORD_FACES,
		WORD_VERTEX_POSITIONS_ID,
		WORD_BONES_WEIGHT,
		WORD_ARMATURE,
		WORD_BONE,
		WORD_NAME,
		WORD_ACTIONS,
		WORD_POS_X,
		WORD_POS_Y,
		WORD_POS_Z,
		WORD_ROT_W,
		WORD_ROT_X,
		WORD_ROT_Y,
		WORD_ROT_Z,
		WORD_PARENT,
		WORD_TEXTURE_COORD,
		WORD_MATERIAL,
		WORD_NORMAL_MAP,
		WORD_DIFFUSE_MAP,
		WORD_MATERIALS,
		WORD_GIMBAL_TRANSFORM,
		WORD_BONE_MATRIX,
		WORD_ACTION,
		WORD_ARMATURES,
		WORD_FRAMES, 
		WORD_TEXTURE,
		WORD_TIMING,
		WORD_PARENT_INVERSED_MATRIX,
		WORD_LENGTH,																								
		WORD_ALPHA,									//	L"*alpha", 
		WORD_AMBIENT,								//	L"*ambient",
		WORD_DARKNESS,								//	L"*darkness",
		WORD_DIFFUSE_COLOR,							//	L"*diffuse_color", 
		WORD_DIFFUSE_FRESNEL,						//	L"*diffuse_fresnel", 
		WORD_DIFFUSE_FRESNEL_FACTOR,				//	L"*diffuse_fresnel_factor",
		WORD_DIFFUSE_INTENSITY,						//	L"*diffuse_intensity",
		WORD_EMIT,									//	L"*emit",
		WORD_MIRROR_COLOR,							//	L"*mirror_color",
		WORD_ROUGHNESS,								//	L"*roughness",
		WORD_SPECULAR_ALPHA,						//	L"*specular_alpha",
		WORD_SPECULAR_COLOR,						//	L"*specular_color",
		WORD_SPECULAR_HARDNESS,						//	L"*specular_hardness",
		WORD_SPECULAR_INTENSITY,					//	L"*specular_intensity",
		WORD_SPECULAR_IOR,							//	L"*specular_ior",
		WORD_SPECULAR_SLOPE,						//	L"*specular_slope",
		WORD_TRANSLUCENCY,							//	L"*translucency",
		WORD_SOUND,
		WORD_FILENAME,
		WORD_VOLUME,
		WORD_PITCH,
		WORD_MAX_DISTANCE,
		WORD_REFERENCE_DISTANCE,
		WORD_CONE_ANGLE_INNER,
		WORD_CONE_ANGLE_OUTER,
		WORD_CONE_VOLUME_OUTER,
		WORD_ATTENUATION,
		WORD_TYPE, 
		WORD_POINT_LIGHT,
		WORD_LIGHT_TYPE,
		WORD_COLOR,
		WORD_DISTANCE,
		WORD_ENERGY,
		WORD_FALLOFF_TYPE,
		WORD_LINEAR_ATTENUATION,
		WORD_QUADRATIC_ATTENUATION,
		WORD_REFERENCE, 
		WORD_BONE_ANIMATION,
		WORD_OBJECT_ANIMATION,
		WORD_POSITION_TRACK,
		WORD_ROTATION_TRACK,
		WORD_MATERIAL_REF,
		WORD_ACTIONS_REF,
		WORD_ACTION_REF,
		WORD_CAMERA,
		WORD_FOV,
		WORD_NEAR_PLANE,
		WORD_FAR_PLANE,
		WORD_FOCUS,
		WORD_ORTHO_SCALE,
		WORD_COLLISION_MESH
	};

	static const wchar_t* Keyword[] = {
		L"",
		L"{",
		L"}",
		L"*object",
		L"*bounding_box",
		L"*location",
		L"*world_matrix",
		L"*local_matrix",
		L"*mesh",
		L"*vertex_position",
		L"*normals",
		L"*faces",
		L"*vertex_positions_id",
		L"*bones_weight",
		L"*armature",
		L"*bone",
		L"*name",
		L"*actions",
		L"*pos_x",
		L"*pos_y",
		L"*pos_z",
		L"*rot_w",
		L"*rot_x",
		L"*rot_y",
		L"*rot_z",
		L"*parent",
		L"*tex_coord",
		L"*material",
		L"*normal_map",
		L"*diffuse_map",
		L"*materials",
		L"*gimbal_transform",
		L"*bone_matrix",
		L"*action",
		L"*armatures",
		L"*frames", 
		L"*texture",
		L"*timing",
		L"*parent_inverse_matrix",
		L"*length",
		L"*alpha", 
		L"*ambient",
		L"*darkness",
		L"*diffuse_color", 
		L"*diffuse_fresnel", 
		L"*diffuse_fresnel_factor",
		L"*diffuse_intensity",
		L"*emit",
		L"*mirror_color",
		L"*roughness",
		L"*specular_alpha",
		L"*specular_color",
		L"*specular_hardness",
		L"*specular_intensity",
		L"*specular_ior",
		L"*specular_slope",
		L"*translucency",
		L"*sound",
		L"*filename",
		L"*volume",
		L"*pitch",
		L"*max_distance",
		L"*reference_distance",
		L"*cone_angle_inner",
		L"*cone_angle_outer",
		L"*cone_volume_outer",
		L"*attenuation",
		L"*type",
		L"*point_light",
		L"*light_type",
		L"*color",
		L"*distance",
		L"*energy",
		L"*fallof_type",
		L"*linear_attenuation",
		L"*quadratic_attenuation",
		L"*reference",
		L"*bone_animation",
		L"*object_animation",
		L"*position_track",
		L"*rotation_track",
		L"*material_ref",
		L"*actions_ref",
		L"*action_ref",
		L"*camera",
		L"*fov",
		L"*near",
		L"*far",
		L"*focus",
		L"*ortho_scale",
		L"*collision_mesh"
	};
}

#endif	//	_H_PUNK_VIRTUAL_KEY_WORDS