/*
File: Extensions.cpp
Author:	Abramau Mikalaj
Description: Load OpenGL functions
*/
#include "extensions_win32.h"
#include "../../driver/module.h"
#include "../../../../system/module.h"

namespace GPU
{
	namespace OpenGL
	{
		PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v;
		PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
		PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameterui64v;
		PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv;
		PFNGLTEXPARAMETERIPROC glTexParameteri;
		PFNGLPIXELSTOREIPROC glPixelStorei;
		PFNGLPIXELSTOREFPROC glPixelStoref;
		PFNGLBLENDCOLORPROC glBlendColor;
		PFNGLBLENDEQUATIONPROC glBlendEquation;
		PFNGLBLENDEQUATIONIPROC glBlendEquationi;
		PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
		PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei;
		PFNGLENABLEIPROC glEnablei;
		PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
		PFNGLBLENDFUNCPROC glBlendFunc;
		PFNGLBLENDFUNCIPROC glBlendFunci;
		PFNGLACTIVETEXTUREPROC glActiveTexture;
		PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;
		PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT;
		PFNWGLGETEXTENSIONSSTRINGARBPROC wglGetExtensionsStringARB;
		PFNGLBUFFERDATAPROC glBufferData;
		PFNGLBUFFERSUBDATAPROC glBufferSubData;
		PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData;
		PFNGLGENBUFFERSPROC glGenBuffers;
		PFNGLBINDBUFFERPROC glBindBuffer;
		PFNGLDELETEBUFFERSPROC glDeleteBuffers;
		PFNGLMAPBUFFERPROC glMapBuffer;
		PFNGLUNMAPBUFFERPROC glUnmapBuffer;
		PFNGLISBUFFERPROC glIsBuffer;
		PFNGLISRENDERBUFFERPROC glIsRenderbuffer;
		PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
		PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
		PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
		PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
		PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;
		PFNGLISFRAMEBUFFERPROC glIsFramebuffer;
		PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
		PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
		PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
		PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
		PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture1D;
		PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
		PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;
		PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
		PFNGLCREATESHADERPROC glCreateShader;
		PFNGLCREATEPROGRAMPROC glCreateProgram;
		PFNGLDELETESHADERPROC glDeleteShader;
		PFNGLDELETEPROGRAMPROC glDeleteProgram;
		PFNGLSHADERSOURCEPROC glShaderSource;
		PFNGLCOMPILESHADERPROC glCompileShader;
		PFNGLATTACHSHADERPROC glAttachShader;
		PFNGLDETACHSHADERPROC glDetachShader;
		PFNGLLINKPROGRAMPROC glLinkProgram;
		PFNGLUSEPROGRAMPROC glUseProgram;
		PFNGLVALIDATEPROGRAMPROC glValidateProgram;
		PFNGLUNIFORM1FPROC glUniform1f;
		PFNGLUNIFORM1FVPROC glUniform1fv;
		PFNGLUNIFORM1IPROC glUniform1i;
		PFNGLUNIFORM1IVPROC glUniform1iv;
		PFNGLUNIFORM2FPROC glUniform2f;
		PFNGLUNIFORM2FVPROC glUniform2fv;
		PFNGLUNIFORM2IVPROC glUniform2iv;
		PFNGLUNIFORM3FPROC glUniform3f;
		PFNGLUNIFORM3IVPROC glUniform3iv;
		PFNGLUNIFORM3FVPROC glUniform3fv;
		PFNGLUNIFORM3IPROC glUniform3i;
		PFNGLUNIFORM4FPROC glUniform4f;
		PFNGLUNIFORM4IVPROC glUniform4iv;
		PFNGLUNIFORM4FVPROC glUniform4fv;
		PFNGLUNIFORM4IPROC glUniform4i;
		PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
		PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
		PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
		PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform;
		PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders;
		PFNGLGETSHADERSOURCEPROC glGetShaderSource;
		PFNGLGETUNIFORMFVPROC glGetUniformfv;
		PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
		PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d;
		PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv;
		PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f;
		PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv;
		PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s;
		PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv;
		PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d;
		PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv;
		PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f;
		PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv;
		PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s;
		PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv;
		PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d;
		PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv;
		PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f;
		PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv;
		PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s;
		PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv;
		PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d;
		PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv;
		PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f;
		PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;
		PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s;
		PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv;
		PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
		PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
		PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
		PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
		PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv;
		PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
		PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
		PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv;
		PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib;
		PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
		PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements;
		PFNGLGETSTRINGIPROC glGetStringi;
		PFNGLGETERRORPROC glGetError;
		PFNGLGETINTEGERVPROC glGetIntegerv;
		PFNGLVIEWPORTPROC glViewport;
		PFNGLCLEARCOLORPROC glClearColor;
		PFNGLENABLEPROC glEnable;
		PFNGLDISABLEPROC glDisable;
		PFNGLREADPIXELSPROC glReadPixels;
		PFNGLGETSTRINGPROC glGetString;
		PFNGLGENTEXTURESPROC glGenTextures;
		PFNGLBINDTEXTUREPROC glBindTexture;
		PFNGLTEXPARAMETERFPROC glTexParameterf;
		PFNGLTEXPARAMETERFVPROC glTexParameterfv;
		PFNGLTEXIMAGE2DPROC glTexImage2D;
		PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
		PFNGLDELETETEXTURESPROC glDeleteTextures;
		PFNGLDRAWBUFFERPROC glDrawBuffer;
		PFNGLREADBUFFERPROC glReadBuffer;
		PFNGLGETSHADERIVPROC glGetShaderiv;
		PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
		PFNGLGETPROGRAMIVPROC glGetProgramiv;
		PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
		PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
		PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
		PFNGLDRAWARRAYSPROC glDrawArrays;
		PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect;
		PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
		PFNGLDRAWELEMENTSPROC glDrawElements;
		PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect;
		PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;
		PFNGLCLEARPROC glClear;
		PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D;
		PFNGLPOLYGONMODEPROC glPolygonMode;
		PFNGLFENCESYNCPROC glFenceSync;
		PFNGLWAITSYNCPROC glWaitSync;
		PFNGLDELETESYNCPROC glDeleteSync;
		PFNGLDRAWBUFFERSPROC glDrawBuffers;
		PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample;
		PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer;
		PFNGLDEPTHFUNCPROC glDepthFunc;
		PFNGLDEPTHMASKPROC glDepthMask;
		PFNGLPOINTSIZEPROC glPointSize;
		PFNGLPOINTPARAMETERIVPROC glPointParameteriv;
		PFNGLPOINTPARAMETERIPROC glPointParameteri;
		PFNGLPOINTPARAMETERFVPROC glPointParameterfv;
		PFNGLPOINTPARAMETERFPROC glPointParameterf;
		PFNGLCULLFACEPROC glCullFace;
		PFNGLLINEWIDTHPROC glLineWidth;
		PFNGLCLEARDEPTHFPROC glClearDepthf;
		PFNGLCLEARDEPTHPROC glClearDepth;

        PROC WINAPI (*wglGetProcAddress(LPCSTR));

		bool IsSupported(const char* extension, VideoDriver* driver)
		{
			const char* allWgl = wglGetExtensionsStringARB(::GetDC(*driver->GetWindow()));
			int num;
			glGetIntegerv(GL_NUM_EXTENSIONS, &num);
			const char* ptr;
			const char* start;
			start = allWgl;
			for (int i = 0; i < num; i++)
			{
				const char* ext = (const char*)glGetStringi(GL_EXTENSIONS, i);
				if ((ptr = strstr(extension, ext)) != NULL)
				{
					const char* end = ptr + strlen(extension);
					if (isspace(*end) || *end == '\0')
					{
						out_message() << System::string::Format(L"[Video] %s is supported", System::string(extension).Data()) << std::endl;
						return true;
					}
				}
			}
			out_warning() << System::string::Format(L"[Video] %s is not supported", System::string(extension).Data()) << std::endl;
			return false;
		};

		void InitExtensions(void* (*GetGPUProcAddres)(const char*))
		{
			wglGetExtensionsStringARB = (PFNWGLGETEXTENSIONSSTRINGARBPROC)GetGPUProcAddres("wglGetExtensionsStringARB");
			glTexParameterf = (PFNGLTEXPARAMETERFPROC)GetGPUProcAddres("glTexParameterf");
			glBindTexture = (PFNGLBINDTEXTUREPROC)GetGPUProcAddres("glBindTexture");
			glGetIntegerv = (PFNGLGETINTEGERVPROC)GetGPUProcAddres("glGetIntegerv");
			wglSwapIntervalEXT = (PFNWGLSWAPINTERVALEXTPROC)GetGPUProcAddres("wglSwapIntervalEXT");
			glGetStringi = (PFNGLGETSTRINGIPROC)GetGPUProcAddres("glGetStringi");
			glGetError = (PFNGLGETERRORPROC)GetGPUProcAddres("glGetError");
			glDrawRangeElements = (PFNGLDRAWRANGEELEMENTSPROC)GetGPUProcAddres("glDrawRangeElements");
			glViewport = (PFNGLVIEWPORTPROC)GetGPUProcAddres("glViewport");
			glClearColor = (PFNGLCLEARCOLORPROC)GetGPUProcAddres("glClearColor");
			glEnable = (PFNGLENABLEPROC)GetGPUProcAddres("glEnable");
			glDisable = (PFNGLDISABLEPROC)GetGPUProcAddres("glDisable");
			glReadPixels = (PFNGLREADPIXELSPROC)GetGPUProcAddres("glReadPixels");
			glGetString = (PFNGLGETSTRINGPROC)GetGPUProcAddres("glGetString");
			glGenTextures = (PFNGLGENTEXTURESPROC)GetGPUProcAddres("glGenTextures");
			glBindTexture = (PFNGLBINDTEXTUREPROC)GetGPUProcAddres("glBindTexture");
			glTexParameterf = (PFNGLTEXPARAMETERFPROC)GetGPUProcAddres("glTexParameterf");
			glTexParameterfv = (PFNGLTEXPARAMETERFVPROC)GetGPUProcAddres("glTexParameterfv");
			glTexImage2D = (PFNGLTEXIMAGE2DPROC)GetGPUProcAddres("glTexImage2D");
			glFramebufferTexture2D= (PFNGLFRAMEBUFFERTEXTURE2DPROC)GetGPUProcAddres("glFramebufferTexture2D");
			glDeleteTextures = (PFNGLDELETETEXTURESPROC)GetGPUProcAddres("glDeleteTextures");
			glDrawBuffer = (PFNGLDRAWBUFFERPROC)GetGPUProcAddres("glDrawBuffer");
			glReadBuffer = (PFNGLREADBUFFERPROC)GetGPUProcAddres("glReadBuffer");
			glBufferData = (PFNGLBUFFERDATAPROC)GetGPUProcAddres("glBufferData");
			glBufferSubData = (PFNGLBUFFERSUBDATAPROC)GetGPUProcAddres("glBufferSubData");
			glGetBufferSubData = (PFNGLGETBUFFERSUBDATAPROC)GetGPUProcAddres("glGetBufferSubData");
			glGenBuffers = (PFNGLGENBUFFERSPROC)GetGPUProcAddres("glGenBuffers");
			glBindBuffer = (PFNGLBINDBUFFERPROC)GetGPUProcAddres("glBindBuffer");
			glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)GetGPUProcAddres("glDeleteBuffers");
			glMapBuffer = (PFNGLMAPBUFFERPROC)GetGPUProcAddres("glMapBuffer");
			glUnmapBuffer = (PFNGLUNMAPBUFFERPROC)GetGPUProcAddres("glUnmapBuffer");
			glIsBuffer = (PFNGLISBUFFERPROC)GetGPUProcAddres("glIsBuffer");
			glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC)GetGPUProcAddres("glIsRenderbuffer");
			glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)GetGPUProcAddres("glBindRenderbuffer");
			glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)GetGPUProcAddres("glDeleteRenderbuffers");
			glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)GetGPUProcAddres("glGenRenderbuffers");
			glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)GetGPUProcAddres("glRenderbufferStorage");
			glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC)GetGPUProcAddres("glGetRenderbufferParameteriv");
			glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC)GetGPUProcAddres("glIsFramebuffer");
			glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)GetGPUProcAddres("glBindFramebuffer");
			glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)GetGPUProcAddres("glDeleteFramebuffers");
			glGenFramebuffers =  (PFNGLGENFRAMEBUFFERSPROC)GetGPUProcAddres("glGenFramebuffers");
			glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)GetGPUProcAddres("glCheckFramebufferStatus");
			glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)GetGPUProcAddres("glFramebufferRenderbuffer");
			glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)GetGPUProcAddres("glGetFramebufferAttachmentParameteriv");
			glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)GetGPUProcAddres("glGenerateMipmap");;
			glCreateShader = (PFNGLCREATESHADERPROC)GetGPUProcAddres("glCreateShader");
			glCreateProgram = (PFNGLCREATEPROGRAMPROC)GetGPUProcAddres("glCreateProgram");
			glDeleteProgram = (PFNGLDELETEPROGRAMPROC)GetGPUProcAddres("glDeleteProgram");
			glDeleteShader = (PFNGLDELETESHADERPROC)GetGPUProcAddres("glDeleteShader");
			glShaderSource = (PFNGLSHADERSOURCEPROC)GetGPUProcAddres("glShaderSource");
			glCompileShader = (PFNGLCOMPILESHADERPROC)GetGPUProcAddres("glCompileShader");
			glAttachShader = (PFNGLATTACHSHADERPROC)GetGPUProcAddres("glAttachShader");
			glDetachShader = (PFNGLDETACHSHADERPROC)GetGPUProcAddres("glDetachShader");
			glLinkProgram = (PFNGLLINKPROGRAMPROC)GetGPUProcAddres("glLinkProgram");
			glUseProgram = (PFNGLUSEPROGRAMPROC)GetGPUProcAddres("glUseProgram");
			glValidateProgram = (PFNGLVALIDATEPROGRAMPROC)GetGPUProcAddres("glValidateProgram");
			glUniform1f = (PFNGLUNIFORM1FPROC)GetGPUProcAddres("glUniform1f");
			glUniform1fv = (PFNGLUNIFORM1FVPROC )GetGPUProcAddres("glUniform1fv");
			glUniform1i = (PFNGLUNIFORM1IPROC )GetGPUProcAddres("glUniform1i");
			glUniform1iv = (PFNGLUNIFORM1IVPROC )GetGPUProcAddres("glUniform1iv");
			glUniform2f = (PFNGLUNIFORM2FPROC )GetGPUProcAddres("glUniform2f");
			glUniform2fv = (PFNGLUNIFORM2FVPROC )GetGPUProcAddres("glUniform2fv");
			glUniform2iv = (PFNGLUNIFORM2IVPROC )GetGPUProcAddres("glUniform2iv");
			glUniform3f = (PFNGLUNIFORM3FPROC )GetGPUProcAddres("glUniform3f");
			glUniform3iv = (PFNGLUNIFORM3IVPROC )GetGPUProcAddres("glUniform3iv");
			glUniform3fv = (PFNGLUNIFORM3FVPROC )GetGPUProcAddres("glUniform3fv");
			glUniform3i = (PFNGLUNIFORM3IPROC )GetGPUProcAddres("glUniform3i");
			glUniform4f = (PFNGLUNIFORM4FPROC )GetGPUProcAddres("glUniform4f");
			glUniform4iv = (PFNGLUNIFORM4IVPROC )GetGPUProcAddres("glUniform4iv");
			glUniform4fv = (PFNGLUNIFORM4FVPROC )GetGPUProcAddres("glUniform4fv");
			glUniform4i = (PFNGLUNIFORM4IPROC )GetGPUProcAddres("glUniform4i");
			glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC )GetGPUProcAddres("glGetActiveUniform");
			glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC)GetGPUProcAddres("glGetAttachedShaders");
			glGetShaderSource = (PFNGLGETSHADERSOURCEPROC )GetGPUProcAddres("glGetShaderSource");
			glGetUniformfv = (PFNGLGETUNIFORMFVPROC )GetGPUProcAddres("glGetUniformfv");
			glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC )GetGPUProcAddres("glGetUniformLocation");
			glVertexAttrib1d = (PFNGLVERTEXATTRIB1DPROC)GetGPUProcAddres("glVertexAttrib1d");
			glVertexAttrib1dv = (PFNGLVERTEXATTRIB1DVPROC)GetGPUProcAddres("glVertexAttrib1dv");
			glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC)GetGPUProcAddres("glVertexAttrib1f");
			glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC)GetGPUProcAddres("glVertexAttrib1fv");
			glVertexAttrib1s = (PFNGLVERTEXATTRIB1SPROC )GetGPUProcAddres("glVertexAttrib1s");
			glVertexAttrib1sv = (PFNGLVERTEXATTRIB1SVPROC )GetGPUProcAddres("glVertexAttrib1sv");
			glVertexAttrib2d = (PFNGLVERTEXATTRIB2DPROC )GetGPUProcAddres("glVertexAttrib2d");
			glVertexAttrib2dv = (PFNGLVERTEXATTRIB2DVPROC )GetGPUProcAddres("glVertexAttrib2dv");
			glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC )GetGPUProcAddres("glVertexAttrib2f");
			glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC )GetGPUProcAddres("glVertexAttrib2fv");
			glVertexAttrib2s = (PFNGLVERTEXATTRIB2SPROC )GetGPUProcAddres("glVertexAttrib2s");
			glVertexAttrib2sv = (PFNGLVERTEXATTRIB2SVPROC )GetGPUProcAddres("glVertexAttrib2sv");
			glVertexAttrib3d = (PFNGLVERTEXATTRIB3DPROC )GetGPUProcAddres("glVertexAttrib3d");
			glVertexAttrib3dv = (PFNGLVERTEXATTRIB3DVPROC )GetGPUProcAddres("glVertexAttrib3dv");
			glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC )GetGPUProcAddres("glVertexAttrib3f");
			glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC )GetGPUProcAddres("glVertexAttrib3fv");
			glVertexAttrib3s = (PFNGLVERTEXATTRIB3SPROC )GetGPUProcAddres("glVertexAttrib3s");
			glVertexAttrib3sv = (PFNGLVERTEXATTRIB3SVPROC )GetGPUProcAddres("glVertexAttrib3sv");
			glVertexAttrib4d = (PFNGLVERTEXATTRIB4DPROC )GetGPUProcAddres("glVertexAttrib4d");
			glVertexAttrib4dv = (PFNGLVERTEXATTRIB4DVPROC )GetGPUProcAddres("glVertexAttrib4dv");
			glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC )GetGPUProcAddres("glVertexAttrib4f");
			glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC )GetGPUProcAddres("glVertexAttrib4fv");
			glVertexAttrib4s = (PFNGLVERTEXATTRIB4SPROC )GetGPUProcAddres("glVertexAttrib4s");
			glVertexAttrib4sv = (PFNGLVERTEXATTRIB4SVPROC )GetGPUProcAddres("glVertexAttrib4sv");
			glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC )GetGPUProcAddres("glVertexAttribPointer");
			glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC )GetGPUProcAddres("glBindAttribLocation");
			glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC )GetGPUProcAddres("glEnableVertexAttribArray");
			glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC )GetGPUProcAddres("glDisableVertexAttribArray");
			glGetVertexAttribdv = (PFNGLGETVERTEXATTRIBDVPROC )GetGPUProcAddres("glGetVertexAttribdv");
			glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC )GetGPUProcAddres("glGetVertexAttribfv");
			glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC )GetGPUProcAddres("glGetVertexAttribiv");
			glGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC )GetGPUProcAddres("glGetVertexAttribPointerv");
			glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC )GetGPUProcAddres("glGetActiveAttrib");
			glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC)GetGPUProcAddres("glUniformMatrix2fv");
			glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)GetGPUProcAddres("glUniformMatrix3fv");
			glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)GetGPUProcAddres("glUniformMatrix4fv");
			glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC)GetGPUProcAddres("glGetAttribLocation");
			glGetShaderiv = (PFNGLGETSHADERIVPROC)GetGPUProcAddres("glGetShaderiv");
			glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)GetGPUProcAddres("glGetShaderInfoLog");
			glGetProgramiv = (PFNGLGETPROGRAMIVPROC)GetGPUProcAddres("glGetProgramiv");
			glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)GetGPUProcAddres("glGenVertexArrays");
			glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)GetGPUProcAddres("glDeleteVertexArrays");
			glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)GetGPUProcAddres("glBindVertexArray");
			glDrawArrays = (PFNGLDRAWARRAYSPROC)GetGPUProcAddres("glDrawArrays");
			glDrawArraysIndirect = (PFNGLDRAWARRAYSINDIRECTPROC)GetGPUProcAddres("glDrawArraysIndirect");
			glDrawArraysInstanced = (PFNGLDRAWARRAYSINSTANCEDPROC)GetGPUProcAddres("glDrawArraysInstanced");
			glDrawElements = (PFNGLDRAWELEMENTSPROC)GetGPUProcAddres("glDrawElements");
			glDrawElementsIndirect = (PFNGLDRAWELEMENTSINDIRECTPROC)GetGPUProcAddres("glDrawElementsIndirect");
			glDrawElementsInstanced = (PFNGLDRAWELEMENTSINSTANCEDPROC)GetGPUProcAddres("glDrawElementsInstanced");
			glClear = (PFNGLCLEARPROC)GetGPUProcAddres("glClear");
			glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC)GetGPUProcAddres("glCompressedTexImage2D");
			glActiveTexture = (PFNGLACTIVETEXTUREPROC)GetGPUProcAddres("glActiveTexture");
			glGetProgramiv = (PFNGLGETPROGRAMIVPROC)GetGPUProcAddres("glGetProgramiv");
			glBlendFunc = (PFNGLBLENDFUNCPROC)GetGPUProcAddres("glBlendFunc");
			glBlendEquation = (PFNGLBLENDEQUATIONPROC)GetGPUProcAddres("glBlendEquation");
			glBlendEquationi = (PFNGLBLENDEQUATIONIPROC)GetGPUProcAddres("glBlendEquationi");
			glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC)GetGPUProcAddres("glBlendEquationSeparate");
			glBlendEquationSeparatei = (PFNGLBLENDEQUATIONSEPARATEIPROC)GetGPUProcAddres("glBlendEquationSeparatei");
			glEnablei = (PFNGLENABLEIPROC)GetGPUProcAddres("glEnablei");
			glBlendFuncSeparate = (PFNGLBLENDFUNCSEPARATEPROC)GetGPUProcAddres("glBlendFuncSeparate");
			glBlendFunci = (PFNGLBLENDFUNCIPROC)GetGPUProcAddres("glBlendFunci");
			glBlendColor = (PFNGLBLENDCOLORPROC)GetGPUProcAddres("glBlendColor");
			glPixelStorei = (PFNGLPIXELSTOREIPROC)GetGPUProcAddres("glPixelStorei");
			glPixelStoref = (PFNGLPIXELSTOREFPROC)GetGPUProcAddres("glPixelStoref");
			glTexParameteri = (PFNGLTEXPARAMETERIPROC)GetGPUProcAddres("glTexParameteri");
			glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)GetGPUProcAddres("glGenerateMipmap");
			glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC)GetGPUProcAddres("glTexSubImage2D");
			glPolygonMode = (PFNGLPOLYGONMODEPROC)GetGPUProcAddres("glPolygonMode");
			glGetBufferParameteri64v = (PFNGLGETBUFFERPARAMETERI64VPROC)GetGPUProcAddres("glGetBufferParameteri64v");
			glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC)GetGPUProcAddres("glGetBufferParameteriv");
			glGetBufferParameterui64v = (PFNGLGETBUFFERPARAMETERI64VPROC)GetGPUProcAddres("glGetBufferParameterui64v");
			glGetBufferPointerv = (PFNGLGETBUFFERPOINTERVPROC)GetGPUProcAddres("glGetBufferPointerv");
			glFenceSync = (PFNGLFENCESYNCPROC )GetGPUProcAddres("glFenceSync");
			glWaitSync = (PFNGLWAITSYNCPROC)GetGPUProcAddres("glWaitSync");
			glDeleteSync = (PFNGLDELETESYNCPROC)GetGPUProcAddres("glDeleteSync");
			glDrawBuffers = (PFNGLDRAWBUFFERSPROC)GetGPUProcAddres("glDrawBuffers");
			glRenderbufferStorageMultisample = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC)GetGPUProcAddres("glRenderbufferStorageMultisample");
			glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC)GetGPUProcAddres("glBlitFramebuffer");
			glDepthFunc = (PFNGLDEPTHFUNCPROC)GetGPUProcAddres("glDepthFunc");
			glDepthMask = (PFNGLDEPTHMASKPROC)GetGPUProcAddres("glDepthMask");
			glPointSize = (PFNGLPOINTSIZEPROC)GetGPUProcAddres("glPointSize");
			glPointParameteriv = (PFNGLPOINTPARAMETERIVPROC)GetGPUProcAddres("glPointParameteriv");
			glPointParameteri = (PFNGLPOINTPARAMETERIPROC)GetGPUProcAddres("glPointParameteri");
			glPointParameterfv = (PFNGLPOINTPARAMETERFVPROC)GetGPUProcAddres("glPointParameterfv");
			glPointParameterf = (PFNGLPOINTPARAMETERFPROC)GetGPUProcAddres("glPointParameterf");
			glCullFace = (PFNGLCULLFACEPROC)GetGPUProcAddres("glCullFace");
			glLineWidth = (PFNGLLINEWIDTHPROC)GetGPUProcAddres("glLineWidth");
			glClearDepthf = (PFNGLCLEARDEPTHFPROC)GetGPUProcAddres("glClearDepthf");
			glClearDepth = (PFNGLCLEARDEPTHPROC)GetGPUProcAddres("glClearDepth");
		}
	}
}
